name: Deploy Static Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          mkdir /tmp/website
          cp -r index.html style.css script.js /tmp/website/

          git checkout --orphan gh-pages
          git rm -rf .

          cp -r /tmp/website/* .

          git add .
          git commit -m "Deploy static website"
          git push -f origin gh-pages